### ISSUE TITLE
Option to mock the clock for Closer.reopenCircuitCheck

### ISSUE THREAD

**Issue by gavi-anchorlabs** [cep21/circuit#104]
Since we're able to configure the `Timekeeper` for a `Circuit`, it would be helpful if the library also allowed mocking the `TimeAfterFunc` of the `reopenCircuitCheck` field. https://github.com/cep21/circuit/blob/700836dc9a95756136ce20df20ae5d3f3d8b59fd/v3/closers/hystrix/closer.go#L13-L23

https://github.com/cep21/circuit/blob/700836dc9a95756136ce20df20ae5d3f3d8b59fd/v3/faststats/timedcheck.go#L20

Great library!

**Comment by cep21** [comment]
What problem are you trying to solve?  With most testing, I test hystrix internally to this library and test users of hystrix/circuit by stubbing out their own closer logic.

If you needed to do this, I believe the right way to do this would be to modify this struct `ConfigureCloser` with a `TimeAfterFunc ` parameter.

**Comment by chrisguiney** [comment]
I'd also like this -- 

my scenario is that under test, I want to provide a very deterministic clock so that I can focus the test on if my understanding of my configuration matches it's reality, that my fallback gets invoked properly, and that i'm generally using the library correctly.

It was very confusing to me that it wasn't there -- I had configured my circuit with a `GeneralConfiguration` providing a time keeper, and the `hystrix.Opener` accepts a mock function for `Now()`.  I spent some time trying to figure out why the circuit in my test was not opening (it's `SleepWindow` exceeded the time it took for the test to execute) 


happy to  put  together an  MR

**Comment by cep21** [comment]
Deployed in https://github.com/cep21/circuit/releases/tag/v3.2.2
