### ISSUE TITLE
StatSender interface signature has changed

### ISSUE THREAD

**Issue by 7ail** [cep21/circuit#113]
Hi there,

Tried configuring the `StatSender` in `statsdmetrics.CommandFactory{}` and realised the `statsdmetrics.StatSender` interface no longer matches the `StatSender` interface in `go-statsd-client`. 

https://github.com/cactus/go-statsd-client/blob/6348b56a993b50ba0d50dd9c3515c79dab38d639/statsd/client.go#L18-L28

Seems like they've introduced a new variadic parameter for tags at the end

**Comment by cep21** [comment]
Thanks for the update.  I don't think I can change this API to match because it would be a breaking change for users of the library.  I recommend maybe a comment at the interface with a recommendation that people implement a custom metric's collector.

We have one for prometheus [here](https://github.com/jiacai2050/prometrics).  If you want to make one for statsd with the new API, you can reference it and I'll update the docs to point to it as an alternative.

**Comment by cep21** [comment]
Will close as wontfix for v3 since we cannot break people's code, but will address in v4 here: #115
